name: fakenews_detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - cvxopt
  - nltk
  - wordcloud
  - pip
  - pip:
      - kagglehub
